const PDFDocument = require('pdfkit');

function generateCarbonReport(user, entries, stats, recommendations) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(24).fillColor('#059669').text('EcoGuardian', { align: 'center' });
    doc.fontSize(14).fillColor('#666').text('Carbon Footprint Report — SDG 13: Climate Action', { align: 'center' });
    doc.moveDown();

    // User info
    doc.fontSize(12).fillColor('#333');
    doc.text(`Report for: ${user.name}`);
    doc.text(`Email: ${user.email}`);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`);
    doc.text(`Eco Score: ${user.gamification?.ecoScore || 50}/100`);
    doc.moveDown();

    // Summary
    doc.fontSize(16).fillColor('#059669').text('Emission Summary');
    doc.fontSize(12).fillColor('#333');
    doc.text(`Daily Average: ${stats.dailyAvg || 0} kg CO2`);
    doc.text(`Weekly Total: ${stats.weeklyTotal || 0} kg CO2`);
    doc.text(`Monthly Total: ${stats.monthlyTotal || 0} kg CO2`);
    doc.text(`All-Time Total: ${stats.totalEmissions || 0} kg CO2`);
    doc.moveDown();

    // Category breakdown
    doc.fontSize(16).fillColor('#059669').text('Category Breakdown');
    doc.fontSize(12).fillColor('#333');
    const breakdown = stats.categoryBreakdown || {};
    Object.entries(breakdown).forEach(([cat, val]) => {
      doc.text(`${cat.charAt(0).toUpperCase() + cat.slice(1)}: ${val} kg CO2`);
    });
    doc.moveDown();

    // Recent entries
    doc.fontSize(16).fillColor('#059669').text('Recent Activity (Last 7 Days)');
    doc.fontSize(11).fillColor('#333');
    (entries || []).slice(0, 7).forEach((entry) => {
      doc.text(`${new Date(entry.date).toLocaleDateString()}: ${entry.totalEmissions} kg CO2`);
    });
    doc.moveDown();

    // Recommendations
    doc.fontSize(16).fillColor('#059669').text('AI Recommendations');
    doc.fontSize(11).fillColor('#333');
    (recommendations || []).forEach((rec, i) => {
      doc.text(`${i + 1}. ${rec}`);
    });
    doc.moveDown();

    // Footer
    doc.fontSize(10).fillColor('#999').text(
      'Generated by EcoGuardian — Supporting UN SDG 13: Climate Action',
      { align: 'center' }
    );

    doc.end();
  });
}

module.exports = { generateCarbonReport };
